### ISSUE TITLE
Journal entries (16H)

### ISSUE THREAD

**Issue by bbortt** [zeroplexer/ch.bfh.bti7081.s2020.blue#10]
Journaleinträge anzeigen, Journaleintrag erstellen, bearbeiten und löschen. Fullstack Frontend bis Backend bis Datenbank.

**Comment by Marcarrian** [comment]
Noch TODO:

- Confirm Dialog (oder ähnliches beim Löschen eines Journaleintrags)

- Nach dem Erstellen eines Journal zu seiner DetailSeite routen

- Eventuell direkte Formfield Validierung im Frontend: Titel und Inhalt müssen required sein.

- Allgemeines Styling

**Comment by bbortt** [comment]
Die route `http://localhost:8080/journal` existiert auch noch nicht?

**Comment by calesanz** [comment]
Ich habe einige der beschriebenen Probleme/TODOs behoben. 
Styling und UI design fehlt aber noch.
