### ISSUE TITLE
UI Mockups erstellen

### ISSUE THREAD

**Issue by Marcarrian** [zeroplexer/ch.bfh.bti7081.s2020.blue#23]

**Comment by zeroplexer** [comment]
First Mockup to discuss: https://app.moqups.com/6CEa85rsDa/view/page/ae973f342

**Comment by bbortt** [comment]
looks promising to me. maybe you missed some buttons on the list items, in order to change to a more detailed view.

**Comment by Marcarrian** [comment]
Mit einem Klick auf das List-Item navigiert man zu seiner Detailansicht

**Comment by bbortt** [comment]
> Mit einem Klick auf das List-Item navigiert man zu seiner Detailansicht

und wie soll man das auf einem mobile screen bemerken? es braucht schon einen indikator.. ;)

**Comment by Marcarrian** [comment]
Unterstützen wir mobile?

**Comment by bbortt** [comment]
achso, das ist die andere frage.. schauen wir heute abend.

**Comment by zeroplexer** [comment]
Nach Absprache mit dem Team werden wir die Applikation nicht für mobile optimieren. Ansonsten sind die Mockups gut
