### ISSUE TITLE
Authentication service (12H)

### ISSUE THREAD

**Issue by bbortt** [zeroplexer/ch.bfh.bti7081.s2020.blue#5]
Requires: #8 .

**Comment by calesanz** [comment]
Worked 3 Hours
Added basic sign in functionality backed by hard coded user.

- [x] Spring Security setup, routes, authentication
- [ ] Integrate User to Patient model
- [ ] Login use Database
- [ ] Improve Login UI
- [ ] Registration UI
- [ ] Registration using Database
- [ ] Remove or implement reset password
- [ ] Add Userinformation and logout link to navigation

**Comment by bbortt** [comment]
> by hard coded user.

we might even read them from database after #7 .

**Comment by bbortt** [comment]
@calesanz will we use bcrypt? I suggest to do so..

**Comment by calesanz** [comment]
We already use bcrypt [SecurityConfiguration.java](https://github.com/zeroplexer/ch.bfh.bti7081.s2020.blue/blob/f64ce7fb63f42baaca5c07ce08f70a3b31d03dfa/source/src/main/java/ch/bfh/bti7081/s2020/blue/security/SecurityConfiguration.java#L81). For added protection we might opt for scrypt.

**Comment by bbortt** [comment]
I mean hashing it on database layer, not in java. using [PostgreSQL `pgcrypto` extension](https://www.postgresql.org/docs/8.3/pgcrypto.html). It's for sure more secure in almost all aspects.

Hashing and comparing credentials during login is spring security is fine.
