### ISSUE TITLE
Backend - database connection (4H)

### ISSUE THREAD

**Issue by bbortt** [zeroplexer/ch.bfh.bti7081.s2020.blue#9]
Inklusive Auswahl der Datenbank.

Jeder Entwickler muss lokal mit der Datenbank arbeiten können.

**Comment by calesanz** [comment]
Kannst du bitte noch eine Anleitung oder ein Beispiel geben wie wir die Datenbank verwenden können.

- Lokaler Postgres (manuell installiert und konfiguriert?), Postgres als Docker Container?
- Datenbank Verwendung: jdbc und SQL Queries schreiben oder verwenden wir Hibernate oder ein anderes ORM?

**Comment by bbortt** [comment]
mache ich direkt in #7. wir werden flyway verwenden. und ich mache scripts zur erstellung und konfiguration.
du kannst entweder lokal installieren oder als docker container laufen lassen (ich bevorzuge zweiteres). die konfiguration unterscheidet sich aber dann. deshalb würde ich das nicht direkt dokumentieren, ist sache des benutzers.
was denkst du?
